---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devnet-namespace
  name: grafana-pvc
  labels:
    app: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
