---
apiVersion: v1
kind: Service
metadata:
  namespace: devnet-namespace
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
