---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devnet-namespace
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        restartPolicy: Always
        - name: grafana
            image: docker.io/grafana/grafana:8.1.0-ubuntu
            imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: grafana-secrets
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana/
      securityContext:
        fsGroup: 472      
    volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-pvc
          