---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    component: influxdb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: storage/data
    