---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: devnet-namespace
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
          - name: telegraf
            image: docker.io/telegraf:1.19.0
          # envFrom: # if you like to use Telgraf SecretMap instead of InfluxDB SecretMap
          #   - secretRef:
          #       name: telegraf-secrets
          env:
            - name: INFLUXDB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: INFLUXDB_ADMIN_USER
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: INFLUXDB_ADMIN_PASSWORD
            - name: INFLUXDB_HOST
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: INFLUXDB_HOST
            - name: INFLUXDB_DB
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: INFLUXDB_DB
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
