---
apiVersion: v1
kind: Service
metadata:
  namespace: devnet-namespace
  name: telegraf-service
spec:
  selector:
    app: telegraf
  ports:
    - protocol: TCP
      port: 57000
      targetPort: 57000
      nodePort: 32000
  type: LoadBalancer
