---
apiVersion: v1  
kind: Service  
metadata:  
  name: influxdb-svc  
spec:  
  selector:  
    app: influxdb  
  ports:  
    - protocol: TCP  
      port: 8086  
      targetPort: 8086
      # nodePort: 32000 # set this if you have LoadBalancer service type
  type: ClusterIP # can be LoadBalancer, if you are running in the cloud
  