apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    team: netdevops
    app: nginx
spec:
  containers:
    - name: nginx-pod
      image: nginx:latest
      ports:
        - containerPort: 80
